pragma options "--slv-simiters 4 --bnd-inbits 3 --bnd-inline-amnt 8 --bnd-unroll-amnt 4 ";

int TIMESIZE = 4;
int BOUND = 4;
int INTMAX = 7;
int HEAPSIZE = 5;
int LOCVARSIZE = 6;
int INTVARSIZE = 1;
int MBUDGET = 1;

include "header/lseg_header.skh";

int old_sll, old_len, old_min, old_max, old_size, old_height, old_lenseg, old_minseg, old_maxseg;

int rank_func_test = 
LEN;

void snapshot_test(int x, int y, ref int osll, ref int olenseg, ref int ominseg, ref int omaxseg) {
	olenseg = lenseg_comp(locvars[x], locvars[y]);
	ominseg = minseg_comp(locvars[x], locvars[y]);
	omaxseg = maxseg_comp(locvars[x], locvars[y]);
}

bit pre_cond_test(int x, int y) {
	return lseg_inv(x, y);
}

bit post_cond_test(int r, int x, int y, ref int old_lenseg_x_y, ref int old_minseg_x_y, ref int old_maxseg_x_y) {
	return ((lseg_inv(r, x) && (locvar_eq(r, y))) && (lenseg_comp(locvars[r], locvars[x]) == old_lenseg_x_y)) && ((minseg_comp(locvars[r], locvars[x]) == old_minseg_x_y) && (maxseg_comp(locvars[r], locvars[x]) == old_maxseg_x_y));
}

int rank_var_test = 6;
int rank_var_aux_test = {| 1 | 2 | 3 | 4 | 5 |};

int mutate_var_test = {| 1 | 2 | 3 | 4 | 5 |};

bit preserve_sll = false;
bit preserve_len = false;
bit preserve_min = false;
bit preserve_max = false;

bit preserve_lenseg = true;
bit preserve_minseg = true;
bit preserve_maxseg = true;

void guess_ranking_test() {
	assume rank_var_test>0 && rank_var_test<LOCVARSIZE;
	assume rank_var_aux_test>0 && rank_var_aux_test<LOCVARSIZE;
	ranking_snapshot(rank_func_test, rank_var_test, rank_var_aux_test);
}

bit loop_preserves_test() {
	bit single = false;
	int comp1 = {| 1 |};
	int comp2 = comp1 + 1;
	int comp3 = {| 1 | 2 | 3 | 4 | 5 |};
	int comp4 = {| 1 | 2 | 3 | 4 | 5 |};
	return (preserve_sll ? sll_equal_inv(LOCVARSIZE-1) : true)
	  && (preserve_len ? len_preserve_inv(old_len, comp1, comp2, comp3, single) : true)
	  && (preserve_min ? min_preserve_inv(old_min, comp1, comp2, comp3, single) : true)
	  && (preserve_max ? max_preserve_inv(old_max, comp1, comp2, comp3, single) : true)
	  && ((preserve_lenseg && comp3 != comp4) ? lenseg_preserve_inv(old_lenseg, comp1, comp2, comp3, comp4, single) : true)
	  && ((preserve_minseg && comp3 != comp4) ? minseg_preserve_inv(old_minseg, comp1, comp2, comp3, comp4, single) : true)
	  && ((preserve_maxseg && comp3 != comp4) ? maxseg_preserve_inv(old_maxseg, comp1, comp2, comp3, comp4, single) : true)
	;
}

bit loop_inv_test() {
	return loop_preserves_test()
	 && predicate(2, 0, 0, 5, 0)
;
}

bit loop_inv_pre_test() {
	return loop_inv_test();
}

bit loop_inv_post_test() {
	return loop_inv_test()
	  && ranking_decreases(rank_func_test, rank_var_test, rank_var_aux_test);
}

bit loop_cond_test() {
	return ! (locvars[1] == locvars[0] || locvars[1] == locvars[4]);
}

harness void before_loop_test(int[LOCVARSIZE-1] llocvars, int[INTVARSIZE] lintvars, int[HEAPSIZE-1] lnext, int[HEAPSIZE-1] lsupernext, int[HEAPSIZE-1] lkey, bit[HEAPSIZE-1] lsymbolic, bit[HEAPSIZE-1] lactive) {

	int[HEAPSIZE-1] lleft = {};
	int[HEAPSIZE-1] lright = {};
	init(llocvars, lintvars, lnext, lsupernext, lleft, lright, lkey, lsymbolic, lactive);

	assume(basic_assumptions() && basic_axioms());
	assume pre_cond_test(5, 4);
	snapshot_test(5, 4, old_sll, old_lenseg, old_minseg, old_maxseg);

	locVarAssign(2, 0);

	locVarAssign(3, 0);

	locVarAssign(1, 5);


	assertPost(loop_inv_pre_test());
}

harness void iterate_test(int lold_sll, int lold_lenseg, int lold_minseg, int lold_maxseg, int lold_sll, int lold_lenseg, int lold_minseg, int lold_maxseg, int[LOCVARSIZE-1] llocvars, int[INTVARSIZE] lintvars, int[HEAPSIZE-1] lnext, int[HEAPSIZE-1] lsupernext, int[HEAPSIZE-1] lkey, bit[HEAPSIZE-1] lsymbolic, bit[HEAPSIZE-1] lactive) {

	int[HEAPSIZE-1] lleft = {};
	int[HEAPSIZE-1] lright = {};
	init(llocvars, lintvars, lnext, lsupernext, lleft, lright, lkey, lsymbolic, lactive);

	old_sll = lold_sll;
	old_lenseg = lold_lenseg;
	old_minseg = lold_minseg;
	old_maxseg = lold_maxseg;
	old_sll = lold_sll;
	old_lenseg = lold_lenseg;
	old_minseg = lold_minseg;
	old_maxseg = lold_maxseg;

	assume(basic_assumptions() && basic_axioms());
	assume loop_inv_pre_test();
	assume loop_cond_test();
	guess_ranking_test();

	{
	locVarAssign(2, 3);
	locVarAssign(3, 1);
	locderef2var(1, 1);
	locMutate(3, 2, NEXT);

	}


	assertPost(loop_inv_post_test());
}

harness void after_loop_test(int lold_sll, int lold_lenseg, int lold_minseg, int lold_maxseg, int lold_sll, int lold_lenseg, int lold_minseg, int lold_maxseg, int[LOCVARSIZE-1] llocvars, int[INTVARSIZE] lintvars, int[HEAPSIZE-1] lnext, int[HEAPSIZE-1] lsupernext, int[HEAPSIZE-1] lkey, bit[HEAPSIZE-1] lsymbolic, bit[HEAPSIZE-1] lactive) {

	int[HEAPSIZE-1] lleft = {};
	int[HEAPSIZE-1] lright = {};
	init(llocvars, lintvars, lnext, lsupernext, lleft, lright, lkey, lsymbolic, lactive);

	old_sll = lold_sll;
	old_lenseg = lold_lenseg;
	old_minseg = lold_minseg;
	old_maxseg = lold_maxseg;
	old_sll = lold_sll;
	old_lenseg = lold_lenseg;
	old_minseg = lold_minseg;
	old_maxseg = lold_maxseg;

	assume(basic_assumptions() && basic_axioms());
	assume loop_inv_test();
	assume !loop_cond_test();

	ret_loc(3);

	assertPost(post_cond_test(ret, 5, 4, old_lenseg, old_minseg, old_maxseg));
}

